site_name: Fobnail Documentation
site_url: https://fobnail.3mdeb.com/
theme:
    name: material
# TODO: provide logo and styling
#     favicon: images/favicon.png
#     logo: images/logo.png
# extra_css:
#     - stylesheets/extra.css
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
nav:
    - 'Intro': index.md
    - 'Project description': description.md
    - 'Fobnail architecture': architecture.md
    - 'Flashing sample applications': flashing_samples.md
    - 'Environment setup': environment.md
    - 'Resources': resources.md